'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace ServiceReference1
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference1.IService1")>  _
    Public Interface IService1
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Post2", ReplyAction:="http://tempuri.org/IService1/Post2Response")>  _
        Function Post2(ByVal value As String) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/Post2", ReplyAction:="http://tempuri.org/IService1/Post2Response")>  _
        Function Post2Async(ByVal value As String) As System.Threading.Tasks.Task(Of String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/TrnMessage", ReplyAction:="http://tempuri.org/IService1/TrnMessageResponse")>  _
        Function TrnMessage() As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IService1/TrnMessage", ReplyAction:="http://tempuri.org/IService1/TrnMessageResponse")>  _
        Function TrnMessageAsync() As System.Threading.Tasks.Task(Of String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IService1Channel
        Inherits ServiceReference1.IService1, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Service1Client
        Inherits System.ServiceModel.ClientBase(Of ServiceReference1.IService1)
        Implements ServiceReference1.IService1
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function Post2(ByVal value As String) As String Implements ServiceReference1.IService1.Post2
            Return MyBase.Channel.Post2(value)
        End Function
        
        Public Function Post2Async(ByVal value As String) As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.Post2Async
            Return MyBase.Channel.Post2Async(value)
        End Function
        
        Public Function TrnMessage() As String Implements ServiceReference1.IService1.TrnMessage
            Return MyBase.Channel.TrnMessage
        End Function
        
        Public Function TrnMessageAsync() As System.Threading.Tasks.Task(Of String) Implements ServiceReference1.IService1.TrnMessageAsync
            Return MyBase.Channel.TrnMessageAsync
        End Function
    End Class
End Namespace
