'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ArCustomer
    Public Property Customer As String
    Public Property Name As String
    Public Property ShortName As String
    Public Property ExemptFinChg As String
    Public Property MaintHistory As String
    Public Property CustomerType As String
    Public Property MasterAccount As String
    Public Property StoreNumber As String
    Public Property PrtMasterAdd As String
    Public Property CreditStatus As String
    Public Property CreditLimit As Decimal
    Public Property InvoiceCount As Decimal
    Public Property Salesperson As String
    Public Property Salesperson1 As String
    Public Property Salesperson2 As String
    Public Property Salesperson3 As String
    Public Property PriceCode As String
    Public Property CustomerClass As String
    Public Property Branch As String
    Public Property TermsCode As String
    Public Property InvDiscCode As String
    Public Property BalanceType As String
    Public Property Area As String
    Public Property LineDiscCode As String
    Public Property TaxStatus As String
    Public Property TaxExemptNumber As String
    Public Property SpecialInstrs As String
    Public Property PriceCategoryTable As String
    Public Property DateLastSale As Nullable(Of Date)
    Public Property DateLastPay As Nullable(Of Date)
    Public Property OutstOrdVal As Decimal
    Public Property NumOutstOrd As Decimal
    Public Property Telephone As String
    Public Property Contact As String
    Public Property AddTelephone As String
    Public Property Fax As String
    Public Property Telex As String
    Public Property TelephoneExtn As String
    Public Property Currency As String
    Public Property UserField1 As String
    Public Property UserField2 As Decimal
    Public Property GstExemptFlag As String
    Public Property GstExemptNum As String
    Public Property GstLevel As String
    Public Property DetailMoveReqd As String
    Public Property InterfaceFlag As String
    Public Property ContractPrcReqd As String
    Public Property BuyingGroup1 As String
    Public Property BuyingGroup2 As String
    Public Property BuyingGroup3 As String
    Public Property BuyingGroup4 As String
    Public Property BuyingGroup5 As String
    Public Property StatementReqd As String
    Public Property BackOrdReqd As String
    Public Property ShippingInstrs As String
    Public Property ShippingInstrsCod As String
    Public Property StateCode As String
    Public Property DateCustAdded As Nullable(Of Date)
    Public Property StockInterchange As String
    Public Property MaintLastPrcPaid As String
    Public Property IbtCustomer As String
    Public Property SoDefaultDoc As String
    Public Property CounterSlsOnly As String
    Public Property PaymentStatus As String
    Public Property Nationality As String
    Public Property HighestBalance As Decimal
    Public Property CustomerOnHold As String
    Public Property InvCommentCode As String
    Public Property EdiSenderCode As String
    Public Property RelOrdOsValue As Decimal
    Public Property EdiFlag As String
    Public Property SoDefaultType As String
    Public Property Email As String
    Public Property ApplyOrdDisc As String
    Public Property ApplyLineDisc As String
    Public Property FaxInvoices As String
    Public Property FaxStatements As String
    Public Property HighInvDays As Decimal
    Public Property HighInv As String
    Public Property DocFax As String
    Public Property DocFaxContact As String
    Public Property SoldToAddr1 As String
    Public Property SoldToAddr2 As String
    Public Property SoldToAddr3 As String
    Public Property SoldToAddr3Loc As String
    Public Property SoldToAddr4 As String
    Public Property SoldToAddr5 As String
    Public Property SoldPostalCode As String
    Public Property SoldToGpsLat As Decimal
    Public Property SoldToGpsLong As Decimal
    Public Property ShipToAddr1 As String
    Public Property ShipToAddr2 As String
    Public Property ShipToAddr3 As String
    Public Property ShipToAddr3Loc As String
    Public Property ShipToAddr4 As String
    Public Property ShipToAddr5 As String
    Public Property ShipPostalCode As String
    Public Property ShipToGpsLat As Decimal
    Public Property ShipToGpsLong As Decimal
    Public Property State As String
    Public Property CountyZip As String
    Public Property City As String
    Public Property State1 As String
    Public Property CountyZip1 As String
    Public Property City1 As String
    Public Property DefaultOrdType As String
    Public Property PoNumberMandatory As String
    Public Property CreditCheckFlag As String
    Public Property CompanyTaxNumber As String
    Public Property DeliveryTerms As String
    Public Property TransactionNature As Decimal
    Public Property DeliveryTermsC As String
    Public Property TransactionNatureC As Decimal
    Public Property RouteCode As String
    Public Property FaxQuotes As String
    Public Property RouteDistance As Decimal
    Public Property TpmCustomerFlag As String
    Public Property SalesWarehouse As String
    Public Property TpmPricingFlag As String
    Public Property ArStatementNo As String
    Public Property TpmCreditCheck As String
    Public Property WholeOrderShipFlag As String
    Public Property MinimumOrderValue As Decimal
    Public Property MinimumOrderChgCod As String
    Public Property UkVatFlag As String
    Public Property UkCurrency As String
    Public Property LanguageCode As String
    Public Property ShippingLocation As String
    Public Property AltMethodFlag As String
    Public Property TimeStamp As Byte()
    Public Property SalesAllowed As String
    Public Property UnappPayAllowed As String
    Public Property PaymentsAllowed As String
    Public Property QuotesAllowed As String
    Public Property CrNotesAllowed As String
    Public Property DrNotesAllowed As String
    Public Property QueryAllowed As String

    Public Overridable Property SorMasters As ICollection(Of SorMaster) = New HashSet(Of SorMaster)

End Class
