'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BomStructure
    Public Property ParentPart As String
    Public Property Version As String
    Public Property Release As String
    Public Property Route As String
    Public Property SequenceNum As String
    Public Property Component As String
    Public Property ComVersion As String
    Public Property ComRelease As String
    Public Property EccConsumption As String
    Public Property StructureOnDate As Nullable(Of Date)
    Public Property StructureOffDate As Nullable(Of Date)
    Public Property OpOffsetFlag As String
    Public Property OperationOffset As Decimal
    Public Property QtyPer As Decimal
    Public Property ScrapPercentage As Decimal
    Public Property ScrapQuantity As Decimal
    Public Property SoOptionFlag As String
    Public Property SoPrintFlag As String
    Public Property InclScrapFlag As String
    Public Property ReasonForChange As String
    Public Property RefDesignator As String
    Public Property AssemblyPlace As String
    Public Property ItemNumber As String
    Public Property AutoNarrCode As Decimal
    Public Property ComponentType As String
    Public Property InclKitIssues As String
    Public Property CreateSubJob As String
    Public Property WetWeightPercent As Decimal
    Public Property IncludeBatch As String
    Public Property IncludeFromJob As String
    Public Property IncludeToJob As String
    Public Property FixedQtyPerFlag As String
    Public Property FixedQtyPer As Decimal
    Public Property RollUpCost As String
    Public Property Warehouse As String
    Public Property IgnoreFloorFlag As String
    Public Property CoProductCostVal As String
    Public Property UomFlag As String
    Public Property QtyPerEnt As Decimal
    Public Property ScrapQuantityEnt As Decimal
    Public Property FixedQtyPerEnt As Decimal
    Public Property ProductCode As String
    Public Property LibraryCode As String
    Public Property FirstSeq As Decimal
    Public Property SecondSeq As Decimal
    Public Property TimeStamp As Byte()
    Public Property OvrEccSpecIss As String

End Class
