'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class InvWarehouse
    Public Property StockCode As String
    Public Property Warehouse As String
    Public Property QtyOnHand As Decimal
    Public Property MtdQtyReceived As Decimal
    Public Property MtdQtyAdjusted As Decimal
    Public Property MtdQtyTrf As Decimal
    Public Property MtdQtyIssued As Decimal
    Public Property MtdQtySold As Decimal
    Public Property QtyAllocated As Decimal
    Public Property QtyOnOrder As Decimal
    Public Property QtyOnBackOrder As Decimal
    Public Property MinimumQty As Decimal
    Public Property MaximumQty As Decimal
    Public Property YtdQtySold As Decimal
    Public Property PrevYearQtySold As Decimal
    Public Property OpeningBalance As Decimal
    Public Property YtdUsageValue As Decimal
    Public Property AbcClass As String
    Public Property UnitCost As Decimal
    Public Property DefaultBin As String
    Public Property DateLastSale As Nullable(Of Date)
    Public Property DateLastStockMove As Nullable(Of Date)
    Public Property DateLastCostChange As Nullable(Of Date)
    Public Property DateLastStockCnt As Nullable(Of Date)
    Public Property DateLastPurchase As Nullable(Of Date)
    Public Property QtyInTransit As Decimal
    Public Property TransferValue As Decimal
    Public Property SafetyStockQty As Decimal
    Public Property ReOrderQty As Decimal
    Public Property QtyAllocatedWip As Decimal
    Public Property InterfaceFlag As String
    Public Property CostMultiplier As Decimal
    Public Property LastCostEntered As Decimal
    Public Property MtdSalesValue As Decimal
    Public Property YtdSalesValue As Decimal
    Public Property PrevYtdSalesVal As Decimal
    Public Property QtyInInspection As Decimal
    Public Property PalletQty As Decimal
    Public Property NumMonthsHistory As Decimal
    Public Property YtdQtyIssued As Decimal
    Public Property RequisitionFlag As String
    Public Property SalesQty1 As Decimal
    Public Property SalesQty2 As Decimal
    Public Property SalesQty3 As Decimal
    Public Property SalesQty4 As Decimal
    Public Property SalesQty5 As Decimal
    Public Property SalesQty6 As Decimal
    Public Property SalesQty7 As Decimal
    Public Property SalesQty8 As Decimal
    Public Property SalesQty9 As Decimal
    Public Property SalesQty10 As Decimal
    Public Property SalesQty11 As Decimal
    Public Property SalesQty12 As Decimal
    Public Property UserField1 As String
    Public Property UserField2 As String
    Public Property UserField3 As String
    Public Property TrfSuppliedItem As String
    Public Property DefaultSourceWh As String
    Public Property TrfLeadTime As Decimal
    Public Property TrfCostGlCode As String
    Public Property TrfCostMultiply As Decimal
    Public Property QtyDispatched As Decimal
    Public Property OpenBalQty1 As Decimal
    Public Property OpenBalQty2 As Decimal
    Public Property OpenBalQty3 As Decimal
    Public Property OpenBalQty4 As Decimal
    Public Property OpenBalQty5 As Decimal
    Public Property OpenBalQty6 As Decimal
    Public Property OpenBalQty7 As Decimal
    Public Property OpenBalQty8 As Decimal
    Public Property OpenBalQty9 As Decimal
    Public Property OpenBalQty10 As Decimal
    Public Property OpenBalQty11 As Decimal
    Public Property OpenBalQty12 As Decimal
    Public Property OpenBalCost1 As Decimal
    Public Property OpenBalCost2 As Decimal
    Public Property OpenBalCost3 As Decimal
    Public Property OpenBalCost4 As Decimal
    Public Property OpenBalCost5 As Decimal
    Public Property OpenBalCost6 As Decimal
    Public Property OpenBalCost7 As Decimal
    Public Property OpenBalCost8 As Decimal
    Public Property OpenBalCost9 As Decimal
    Public Property OpenBalCost10 As Decimal
    Public Property OpenBalCost11 As Decimal
    Public Property OpenBalCost12 As Decimal
    Public Property AgedQty1 As Decimal
    Public Property AgedQty2 As Decimal
    Public Property AgedQty3 As Decimal
    Public Property AgedQty4 As Decimal
    Public Property AgedQty5 As Decimal
    Public Property AgedQty6 As Decimal
    Public Property TrfReplenishWh As Decimal
    Public Property TrfBuyingRule As String
    Public Property TrfDockToStock As Decimal
    Public Property TrfFixTimePeriod As Decimal
    Public Property LabourCost As Decimal
    Public Property MaterialCost As Decimal
    Public Property FixedOverhead As Decimal
    Public Property VariableOverhead As Decimal
    Public Property StdLabCostsBill As Decimal
    Public Property SubContractCost As Decimal
    Public Property DateWhAdded As Nullable(Of Date)
    Public Property RmaQtyIssued As Decimal
    Public Property LastExtendedCost As Decimal
    Public Property OrderPolicy As String
    Public Property MajorOrderMult As Decimal
    Public Property MinorOrderMult As Decimal
    Public Property OrderMinimum As Decimal
    Public Property OrderMaximum As Decimal
    Public Property OrderFixPeriod As Decimal
    Public Property ManualCostFlag As String
    Public Property LeadTime As Decimal
    Public Property ManufLeadTime As Decimal
    Public Property TransferCost As Decimal
    Public Property ImplosionNum As Decimal
    Public Property ExcludeFromSched As String
    Public Property QtyWipReserved As Decimal
    Public Property Supplier As String
    Public Property TimeStamp As Byte()

    Public Overridable Property InvMaster As InvMaster
    Public Overridable Property SorDetails As ICollection(Of SorDetail) = New HashSet(Of SorDetail)

End Class
