'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SorDetail
    Public Property SalesOrder As String
    Public Property SalesOrderLine As Decimal
    Public Property LineType As String
    Public Property MStockCode As String
    Public Property MStockDes As String
    Public Property MWarehouse As String
    Public Property MBin As String
    Public Property MOrderQty As Decimal
    Public Property MShipQty As Decimal
    Public Property MBackOrderQty As Decimal
    Public Property MUnitCost As Decimal
    Public Property MBomFlag As String
    Public Property MParentKitType As String
    Public Property MQtyPer As Decimal
    Public Property MScrapPercentage As Decimal
    Public Property MPrintComponent As String
    Public Property MComponentSeq As String
    Public Property MQtyChangesFlag As String
    Public Property MOptionalFlag As String
    Public Property MDecimals As Decimal
    Public Property MOrderUom As String
    Public Property MStockQtyToShp As Decimal
    Public Property MStockingUom As String
    Public Property MConvFactOrdUm As Decimal
    Public Property MMulDivPrcFct As String
    Public Property MPrice As Decimal
    Public Property MPriceUom As String
    Public Property MCommissionCode As String
    Public Property MDiscPct1 As Decimal
    Public Property MDiscPct2 As Decimal
    Public Property MDiscPct3 As Decimal
    Public Property MDiscValFlag As String
    Public Property MDiscValue As Decimal
    Public Property MProductClass As String
    Public Property MTaxCode As String
    Public Property MLineShipDate As Nullable(Of Date)
    Public Property MAllocStatSched As String
    Public Property MFstTaxCode As String
    Public Property MStockUnitMass As Decimal
    Public Property MStockUnitVol As Decimal
    Public Property MPriceCode As String
    Public Property MConvFactAlloc As Decimal
    Public Property MMulDivQtyFct As String
    Public Property MTraceableType As String
    Public Property MMpsFlag As String
    Public Property MPickingSlip As String
    Public Property MMovementReqd As String
    Public Property MSerialMethod As String
    Public Property MZeroQtyCrNote As String
    Public Property MAbcApplied As String
    Public Property MMpsGrossReqd As String
    Public Property MContract As String
    Public Property MBuyingGroup As String
    Public Property MCusSupStkCode As String
    Public Property MCusRetailPrice As Decimal
    Public Property MTariffCode As String
    Public Property MLineReceiptDat As Nullable(Of Date)
    Public Property MLeadTime As Decimal
    Public Property MTrfCostMult As Decimal
    Public Property MSupplementaryUn As String
    Public Property MReviewFlag As String
    Public Property MReviewStatus As String
    Public Property MInvoicePrinted As String
    Public Property MDelNotePrinted As String
    Public Property MOrdAckPrinted As String
    Public Property MHierarchyJob As String
    Public Property MCustRequestDat As Nullable(Of Date)
    Public Property MLastDelNote As String
    Public Property MUserDef As String
    Public Property MQtyDispatched As Decimal
    Public Property MDiscChanged As String
    Public Property MCreditOrderNo As String
    Public Property MCreditOrderLine As Decimal
    Public Property MUnitQuantity As String
    Public Property MConvFactUnitQ As Decimal
    Public Property MAltUomUnitQ As String
    Public Property MDecimalsUnitQ As Decimal
    Public Property MEccFlag As String
    Public Property MVersion As String
    Public Property MRelease As String
    Public Property MCommitDate As Nullable(Of Date)
    Public Property QtyReserved As Decimal
    Public Property NComment As String
    Public Property NCommentFromLin As Decimal
    Public Property NMscChargeValue As Decimal
    Public Property NMscProductCls As String
    Public Property NMscChargeCost As Decimal
    Public Property NMscInvCharge As String
    Public Property NCommentType As String
    Public Property NMscTaxCode As String
    Public Property NMscFstCode As String
    Public Property NCommentTextTyp As String
    Public Property NMscChargeQty As Decimal
    Public Property NSrvIncTotal As String
    Public Property NSrvSummary As String
    Public Property NSrvChargeType As String
    Public Property NSrvParentLine As Decimal
    Public Property NSrvUnitPrice As Decimal
    Public Property NSrvUnitCost As Decimal
    Public Property NSrvQtyFactor As Decimal
    Public Property NSrvApplyFactor As String
    Public Property NSrvDecimalRnd As Decimal
    Public Property NSrvDecRndFlag As String
    Public Property NSrvMinValue As Decimal
    Public Property NSrvMaxValue As Decimal
    Public Property NSrvMulDiv As String
    Public Property NPrtOnInv As String
    Public Property NPrtOnDel As String
    Public Property NPrtOnAck As String
    Public Property NTaxAmountFlag As String
    Public Property NDepRetFlagProj As String
    Public Property NRetentionJob As String
    Public Property NSrvMinQuantity As Decimal
    Public Property NChargeCode As String
    Public Property IncludeInMrp As String
    Public Property ProductCode As String
    Public Property LibraryCode As String
    Public Property MaterialAllocLine As String
    Public Property ScrapQuantity As Decimal
    Public Property FixedQtyPerFlag As String
    Public Property FixedQtyPer As Decimal
    Public Property MultiShipCode As String
    Public Property User1 As String
    Public Property CreditReason As String
    Public Property OrigShipDateAps As Nullable(Of Date)
    Public Property TpmUsageFlag As String
    Public Property PromotionCode As String
    Public Property TpmSequence As Decimal
    Public Property SalesOrderInitLine As Decimal
    Public Property PreactorPriority As Decimal
    Public Property SalesOrderDetStat As String
    Public Property SalesOrderResStat As String
    Public Property QtyReservedShip As Decimal
    Public Property TimeStamp As Byte()

    Public Overridable Property InvMaster As InvMaster
    Public Overridable Property InvWarehouse As InvWarehouse
    Public Overridable Property SorMaster As SorMaster

End Class
