'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class SorMaster
    Public Property SalesOrder As String
    Public Property NextDetailLine As Decimal
    Public Property OrderStatus As String
    Public Property ActiveFlag As String
    Public Property CancelledFlag As String
    Public Property DocumentType As String
    Public Property Customer As String
    Public Property Salesperson As String
    Public Property CustomerPoNumber As String
    Public Property OrderDate As Nullable(Of Date)
    Public Property EntrySystemDate As Nullable(Of Date)
    Public Property ReqShipDate As Nullable(Of Date)
    Public Property DateLastDocPrt As Nullable(Of Date)
    Public Property ShippingInstrs As String
    Public Property ShippingInstrsCod As String
    Public Property AltShipAddrFlag As String
    Public Property InvoiceCount As Decimal
    Public Property InvTermsOverride As String
    Public Property CreditAuthority As String
    Public Property Branch As String
    Public Property SpecialInstrs As String
    Public Property EntInvoice As String
    Public Property EntInvoiceDate As Nullable(Of Date)
    Public Property DiscPct1 As Decimal
    Public Property DiscPct2 As Decimal
    Public Property DiscPct3 As Decimal
    Public Property OrderType As String
    Public Property TaxExemptFlag As String
    Public Property Area As String
    Public Property TaxExemptNumber As String
    Public Property TaxExemptOverride As String
    Public Property CashCredit As String
    Public Property Warehouse As String
    Public Property LastInvoice As String
    Public Property ScheduledOrdFlag As String
    Public Property GstExemptFlag As String
    Public Property GstExemptNum As String
    Public Property GstExemptORide As String
    Public Property IbtFlag As String
    Public Property OrdAcknwPrinted As String
    Public Property DetCustMvmtReqd As String
    Public Property DocumentFormat As String
    Public Property FixExchangeRate As String
    Public Property ExchangeRate As Decimal
    Public Property MulDiv As String
    Public Property Currency As String
    Public Property GstDeduction As String
    Public Property OrderStatusFail As String
    Public Property ConsolidatedOrder As String
    Public Property CreditedInvDate As Nullable(Of Date)
    Public Property Job As String
    Public Property SerialisedFlag As String
    Public Property CounterSalesFlag As String
    Public Property Nationality As String
    Public Property DeliveryTerms As String
    Public Property TransactionNature As Decimal
    Public Property TransportMode As Decimal
    Public Property ProcessFlag As Decimal
    Public Property JobsExistFlag As String
    Public Property AlternateKey As String
    Public Property LastOperator As String
    Public Property HierarchyFlag As String
    Public Property DepositFlag As String
    Public Property EdiSource As String
    Public Property DeliveryNote As String
    Public Property [Operator] As String
    Public Property LineComp As String
    Public Property CaptureHh As Decimal
    Public Property CaptureMm As Decimal
    Public Property LastDelNote As Nullable(Of Date)
    Public Property TimeDelPrtedHh As Decimal
    Public Property TimeDelPrtedMm As Decimal
    Public Property TimeInvPrtedHh As Decimal
    Public Property TimeInvPrtedMm As Decimal
    Public Property DateLastInvPrt As Nullable(Of Date)
    Public Property Salesperson2 As String
    Public Property Salesperson3 As String
    Public Property Salesperson4 As String
    Public Property CommissionSales1 As Decimal
    Public Property CommissionSales2 As Decimal
    Public Property CommissionSales3 As Decimal
    Public Property CommissionSales4 As Decimal
    Public Property TimeTakenToAdd As Decimal
    Public Property TimeTakenToChg As Decimal
    Public Property FaxInvInBatch As String
    Public Property InterWhSale As String
    Public Property SourceWarehouse As String
    Public Property TargetWarehouse As String
    Public Property DispatchesMade As String
    Public Property LiveDispExist As String
    Public Property NumDispatches As Decimal
    Public Property CustomerName As String
    Public Property ShipAddress1 As String
    Public Property ShipAddress2 As String
    Public Property ShipAddress3 As String
    Public Property ShipAddress3Loc As String
    Public Property ShipAddress4 As String
    Public Property ShipAddress5 As String
    Public Property ShipPostalCode As String
    Public Property ShipToGpsLat As Decimal
    Public Property ShipToGpsLong As Decimal
    Public Property State As String
    Public Property CountyZip As String
    Public Property ExtendedTaxCode As String
    Public Property MultiShipCode As String
    Public Property WebCreated As String
    Public Property Quote As String
    Public Property QuoteVersion As Decimal
    Public Property GtrReference As String
    Public Property NonMerchFlag As String
    Public Property Email As String
    Public Property User1 As String
    Public Property CompanyTaxNo As String
    Public Property TpmPickupFlag As String
    Public Property TpmEvaluatedFlag As String
    Public Property StandardComment As String
    Public Property DetailStatus As String
    Public Property SalesOrderSource As String
    Public Property SalesOrderSrcDesc As String
    Public Property LanguageCode As String
    Public Property ShippingLocation As String
    Public Property IncludeInMrp As String
    Public Property TimeStamp As Byte()

    Public Overridable Property ArCustomer As ArCustomer
    Public Overridable Property SorDetails As ICollection(Of SorDetail) = New HashSet(Of SorDetail)

End Class
